theme: jekyll-theme-leap-day
keywords: anroid, android development, ios
description: Insights about mobile development
---
layout: post
title: "码农的救赎：使用Github Pages搭建博客"
date: 2014-10-16 22:18:36 +0800
comments: true
categories: miscellaneous
keywords: Github IO, octopress, jekyll, ruby, github
description: 使用Github来搭建博客，像写代码一样写博客，用版本控制来管理博客
---
<section>
    <h1>Categories</h1>
    <ul id="categories">
        {% for category in site.categories %}
            <li class="category">
                {% capture category_url %}/blog/categories//index.html{% endcapture %}
                <a class="list-group-item {% if category_url == page.url %}active{% endif %}" href=""></a>
            </li>
        {% endfor %}
    </ul>
</section>